GET  http://localhost:1338/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGVsbGUxIiwicm9sZSI6IlBNIiwiaWF0IjoxNjk1NjU4NTE2fQ.9nxXoLdk-KzutcDibKp8TzfVv7-bk6QPv-NDSKfsr_c
###

POST http://localhost:1338/add-team-member HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMDAwIiwibmFtZSI6IlBlbGxlMSIsInJvbGUiOiJQTSIsImlhdCI6MTY5NjIyMjEyNiwiZXhwIjoxNjk2MzA4NTI2fQ.oZEftCar1CQ0BGeVKK-FZy6MprZ_4nB6sdAnl2B-1tk

{
    "add_new_members":[["'asddsa'","'asdasd'"],["aaaaaaaaa", "bbbbbbbbbbbbb"]]
}
